#所有环境的公共配置
server:
  port: 20000
  servlet:
    context‐path: /security-springboot

# 应用名称
spring:
  application:
    name: catharine-demo-service
  datasource:
    url: ${catharine.datasource.dev.url}
    username: ${catharine.datasource.dev.username}
    password: ${catharine.datasource.dev.password}
#    driver-class-name: ${catharine.datasource.dev.driver-class-name}com.alibaba.druid.proxy.DruidDriver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.alibaba.druid.proxy.DruidDriver

  mvc:
    view:
      prefix: /WEB‐INF/views/
      suffix: .jsp

info:
  app-name: catharine-demo-service
  author: liuzhi
  email: liuzhi0621@gmail.com