#所有环境的公共配置
server:
  port: 20003
# 应用名称
spring:
  application:
    name: catharine-user
  datasource:
    url: ${catharine.datasource.dev.url}
    username: ${catharine.datasource.dev.username}
    password: ${catharine.datasource.dev.password}


info:
  app-name: catharine-user-service
  author: liuzhi
  email: liuzhi0621@gmail.com
debug: true